name: Build-OpenWrt-lede-b1

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '0 18 * * 0,2,4,5,6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIN_PATH: /home/runner/work/hiwifi_hc5962-openwrt/hiwifi_hc5962-openwrt/lede/bin

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli \
          dotnet* powershell ruby-full zulu* llvm*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build lede
        run: |
          chmod +x build.sh && ./build.sh

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: hiwifi_hc5962-Packages-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v3
        with:
          name: hiwifi_hc5962-Firmwares-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-hiwifi_hc5962-squashfs-sysupgrade.bin

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-hiwifi_hc5962.manifest
